//! Embedded skill assets and small accessors over them.
//!
//! The `SKILL_FILES` / `COMMAND_FILES` tables are generated by `build.rs` from
//! the canonical skill source under `assets/skill` and `assets/plugin-commands`.

include!(concat!(env!("OUT_DIR"), "/skill_assets.rs"));

/// The relative path of the skill's entry file within `SKILL_FILES`.
pub const SKILL_ENTRY: &str = "SKILL.md";

/// Look up an embedded skill file by its relative path.
pub fn skill_file(rel: &str) -> Option<&'static str> {
    SKILL_FILES
        .iter()
        .find(|(name, _)| *name == rel)
        .map(|(_, body)| *body)
}

/// The raw `SKILL.md` (with its YAML frontmatter), as authored.
pub fn skill_md_raw() -> &'static str {
    skill_file(SKILL_ENTRY).unwrap_or("")
}

/// The `SKILL.md` body with any leading YAML frontmatter removed.
pub fn skill_md_body() -> &'static str {
    strip_frontmatter(skill_md_raw())
}

/// The `description:` field from the skill frontmatter, if present.
pub fn skill_description() -> Option<String> {
    frontmatter(skill_md_raw()).and_then(|fm| {
        fm.lines()
            .find_map(|l| l.trim().strip_prefix("description:"))
            .map(|v| unquote(v.trim()))
    })
}

/// Split a `---\n…\n---\n` frontmatter block off the front of `s`.
/// Returns `(frontmatter_without_fences, body)`.
fn split_frontmatter(s: &str) -> (Option<&str>, &str) {
    let Some(rest) = s.strip_prefix("---\n") else {
        return (None, s);
    };
    match rest.find("\n---") {
        Some(end) => {
            let fm = &rest[..end];
            // Body begins after the closing fence line.
            let after = &rest[end + "\n---".len()..];
            let body = after.strip_prefix('\n').unwrap_or(after);
            let body = body.strip_prefix('\n').unwrap_or(body);
            (Some(fm), body)
        }
        None => (None, s),
    }
}

fn frontmatter(s: &str) -> Option<&str> {
    split_frontmatter(s).0
}

fn strip_frontmatter(s: &str) -> &str {
    split_frontmatter(s).1
}

/// Strip a single pair of surrounding double or single quotes.
fn unquote(s: &str) -> String {
    let bytes = s.as_bytes();
    if bytes.len() >= 2 {
        let first = bytes[0];
        let last = bytes[bytes.len() - 1];
        if (first == b'"' && last == b'"') || (first == b'\'' && last == b'\'') {
            return s[1..s.len() - 1].to_owned();
        }
    }
    s.to_owned()
}
