//! `zenith plugin` — install the Zenith agent skill into AI coding tools.
//!
//! Unlike the other command modules (which keep logic pure and leave file I/O
//! to the dispatcher), installing a skill *is* filesystem work, so this module
//! is self-contained: it resolves targets, writes/removes files idempotently,
//! prints a report, and returns an exit code. The dispatcher in `lib.rs` only
//! translates clap arguments into a [`run::Targets`] selection.
//!
//! - `agent` — the supported agents and how each consumes a skill.
//! - `paths` — per-(agent, scope) target paths.
//! - `assets` — the embedded skill tree (generated by `build.rs`).
//! - `render` — single-file rendering for rule-format agents.
//! - `install` / `uninstall` — idempotent writes / removals.
//! - `detect` — which agents are present / already installed.
//! - `run` — orchestration entry points used by `lib.rs`.

pub mod agent;
pub mod assets;
pub mod detect;
pub mod install;
pub mod paths;
pub mod render;
pub mod run;
pub mod uninstall;

pub use agent::{Agent, Scope};
pub use run::{Targets, run_install, run_list, run_uninstall};
